utils: evl-trace: better detect tracefs mountpoint
Finding /sys/kernel/tracing is no guarantee that tracefs is mounted
over this directory, we need to check for /sys/kernel/tracing/evl
instead so that we may assume a legacy debugfs mountpoint if not
found, in last resort only.

Signed-off-by: Philippe Gerum <rpm@xenomai.org>

diff --git a/utils/evl-trace b/utils/evl-trace
--- a/utils/evl-trace
+++ b/utils/evl-trace
@@ -85,7 +85,7 @@ if test \! -d $EVL_TRACEDIR; then
 fi
 
 if test \! -d $EVL_TRACEDIR/events/evl; then
-   echo >&2 "no EVL core in kernel"
+   echo >&2 "no EVL tracepoints ($EVL_TRACEDIR/events/evl is missing)"
    exit 2
 fi
 
